### ISSUE TITLE
Contribution Spell Database?

### ISSUE THREAD

**Issue by Tribunate** [chrisliebaer/FailFeed#14]
Hey there,

I am a contributor to Details: Elitism (and to ElitismHelper, mostly due to similarities). You used one of my PRs to update FailFeed for DF S4.

You listed moving away from ElitismHelper's database as one of your goals. Now, I am just a lowly spell ID wizard and have no clue about licensing or programming. Would it help you in any way, if I'd provide you with my work directly similar to what I do for aforementioned addons? Any other way I might be of help?

PS: Oh, hi, fellow KITler. The world indeed is tiny.

**Comment by chrisliebaer** [comment]
This is indeed a funny coincidence. Just a few days ago I checked if the Details version does have updated spell ids, since EH is almost unmaintained. The Details plugin appears to be using the exact same format as ElitismHelper, so I can probably just point my script there and can the same database. If you want to, you can simply open a PR for TWW S1 and update the [EHDB.lua](https://github.com/chrisliebaer/FailFeed/blob/master/db/EHDB.lua) file. Ignore the warning about the auto generated file. Alternatively tell me once the details plugin has been updated.

The bigger issue has been getting updated spells. I think I spend quite some time in season 3, digging through logs. There are often times up to four spells with the same name or same description. Ideally there would be a database with avoidable spells and various flags (like `almost impossible to avoid`, `easy to avoid`, `requires racial/class ability`, etc.). At least for my use case.

I think there is some potential for a library or database of such spells that can easily be maintained in one place and be used by multiple addons. But this requires some infrastructure and I also really haven't started advertising FailFeed anywhere really. So I have no idea how big the demand for this kind of feature really is. There are also some code quality issues, since I don't have any prior knowledge about structuring WoW addons.

The license issue is just a minor thing. I took some code from EH verbatim and as long as that code is there it's the right thing to respect the chosen license even if it's unlikely anyone cares.

**Comment by Tribunate** [comment]
I opened PRs for both addons just earlier today. I'll just inform you if either is merged for now. Or you can point to my Details Elitism fork, which is my personal focus to keep as up to date as possible.
Just be aware that Details Elitism uses an archival system and only contains data for current/relevant dungeons.

Regarding a universal shared database: This would indeed be cool, but I feel like this would probably be overkill. There aren't too many addons trying to track this stuff (I say that without having known FailFeed before, though). And most of them will use similar formatting. I know WindDungeonHelper uses a different syntax.

I like your thinking trying to tag the avoidable damage depending on circumstance, though. Something that would massively elevate the power of any avoidable damage tracker is the access to the player's buff/debuff state in the moment of the damage event (or probably even slightly before for grace period/travel time/timing purposes). There are just too damn many abilities that are unavoidable for the targeted player, but should be avoided for everyone else. I simply cannot include them in Details Elitism, as false positives are much worse than false negatives in my opinion (and would be sooo much worse for the blame game). I know that Details Elitism tried to dabble in something similar in their raid module, but I have personally never tested that and don't even know if their syntax is hooked up or works.

Anyway, what you describe as difficult and tedious, I have become quite good at: identifying the correct spell ID for a particular part of an ability. And I probably enjoy the process much more than is healthy ...
So, if you ever feel the itch to do something along those lines and provide a framework, just let me know and I'll gladly help fill the data.
